Repository pyladiesbkk/pyladies-web, pull requests merged in 2019-10, with the labels that each got.

#11 Create simple layout
  src/about.html
  src/banner.html
  src/code-of-conduct.html
  src/gallery.html
  src/index.html
  src/location.html
  src/organizer.html
Labels: enhancement

#4 Update pan to contributor in readme
  README.md
Labels: good first issue

#72 [59] write project setup instructions
  README.md
Labels: documentation
